Im unable to use the delete button #7
Klectr/KlectrRadio pull request #11
Opened 2024-03-18 04:06 UTC by jeevikasirwani

added a handler function

2024-03-18 23:00 UTC, tristonarmstrong requested changes
Nice work, but needs a few changes:
- [ ] fix onclick handler to use correct attribute
- [ ] fix handler delete function to use correct properties on `useStationsStore`
- [ ] update the `useStationsStore`  store object's `delete` method to properly write to file

2024-03-18 23:00 UTC, tristonarmstrong commented on src/pages/Main.tsx
> +  useStationsStore.method.remove(id)
`.method` isn't a valid property on `useStationsStore`. Its `methods`. Easy mistake.

Tho, `.remove` isnt even a property on `methods` at all.. You'll need to head on over to `src/hooks/stationStores.ts` and you'll see that theres a `delete` function on there already. Tho it'll need to be modified so it correctly updates the file that stores  all of the stations.

2024-03-18 23:00 UTC, tristonarmstrong commented on src/pages/Main.tsx
> +              <button onClick={()=>handler_delete(s.id)} className="border border-red-500 rounded w-full text-red-500 px-4">Delete</button>
`onClick`  is not a valid attribute on button. May need to enable your LSP

2024-03-21 04:14 UTC, jeevikasirwani commented on src/pages/Main.tsx
> +  useStationsStore.method.remove(id)
delete: (stationId) =>
      set(
        (state) => state?.filter((station) => station.id !== stationId) ?? []
      ),
      const updatedStations = useStationsStore.getState();
      try {
        await writeTextFile("stations.json", JSON.stringify(updatedStations));
      } catch (error) {
        console.error("Error writing to file:", error);
      }                                                                                                                                                                                                                                                           so adding a try catch block in useStationsStore delete function.
changes in main.ts                                                                          
   function handler_delete(id:string){
               // Remove the station from the store based on its ID
               useStationsStore.delete(id);
}

2024-03-21 23:50 UTC, tristonarmstrong commented on src/pages/Main.tsx
> +  useStationsStore.method.remove(id)
If you're just asking if this code works, be sure to use backticks, so it looks like this:
```ts
console.log("hello world");
```

2024-03-22 03:23 UTC, closed without merging

2024-03-22 03:24 UTC, tristonarmstrong commented
Closing due to slow iteration and poor communication. Will work on this myself